// 기본 감정 데이터 (1~60)
const baseEmotions = [
  { id: "01", name: "편안한", category: "calm", emoji: "🌿" },
  { id: "02", name: "따뜻한", category: "calm", emoji: "☀️" },
  { id: "03", name: "반가운", category: "positive", emoji: "👋" },
  { id: "04", name: "흥미로운", category: "positive", emoji: "🔍" },
  { id: "05", name: "궁금한", category: "positive", emoji: "🧐" },
  { id: "06", name: "자랑스러운", category: "positive", emoji: "👑" },
  { id: "07", name: "느긋한", category: "calm", emoji: "☕" },
  { id: "08", name: "행복한", category: "positive", emoji: "🥰" },
  { id: "09", name: "신나는", category: "positive", emoji: "🎉" },
  { id: "10", name: "기대되는", category: "positive", emoji: "✨" },
  { id: "11", name: "감사한", category: "positive", emoji: "🙏" },
  { id: "12", name: "통쾌한", category: "positive", emoji: "💥" },
  { id: "13", name: "다정한", category: "positive", emoji: "🌸" },
  { id: "14", name: "재미있는", category: "positive", emoji: "😆" },
  { id: "15", name: "감동한", category: "positive", emoji: "🥺" },
  { id: "16", name: "사랑스러운", category: "positive", emoji: "❤️" },
  { id: "17", name: "뿌듯한", category: "positive", emoji: "🌟" },
  { id: "18", name: "만족스러운", category: "calm", emoji: "😊" },
  { id: "19", name: "든든한", category: "calm", emoji: "🛡️" },
  { id: "20", name: "열중한", category: "positive", emoji: "🔥" },
  { id: "21", name: "창피한/수줍은", category: "negative", emoji: "😳" },
  { id: "22", name: "슬픈", category: "negative", emoji: "💧" },
  { id: "23", name: "지루한", category: "negative", emoji: "🥱" },
  { id: "24", name: "답답한", category: "negative", emoji: "😤" },
  { id: "25", name: "짜증나는", category: "negative", emoji: "💢" },
  { id: "26", name: "서운한", category: "negative", emoji: "🌧️" },
  { id: "27", name: "마음이아픈", category: "negative", emoji: "💔" },
  { id: "28", name: "걱정스러운", category: "negative", emoji: "😟" },
  { id: "29", name: "지친", category: "negative", emoji: "🔋" },
  { id: "30", name: "무서운", category: "negative", emoji: "😱" },
  { id: "31", name: "긴장된", category: "negative", emoji: "😬" },
  { id: "32", name: "불안한", category: "negative", emoji: "😰" },
  { id: "33", name: "외로운", category: "negative", emoji: "🎈" },
  { id: "34", name: "실망스러운", category: "negative", emoji: "😞" },
  { id: "35", name: "화가난", category: "negative", emoji: "😡" },
  { id: "36", name: "후회스러운", category: "negative", emoji: "🌧️" },
  { id: "37", name: "불쾌한", category: "negative", emoji: "😖" },
  { id: "38", name: "괴로운/고통스러운", category: "negative", emoji: "🩹" },
  { id: "39", name: "미안한", category: "negative", emoji: "🙇" },
  { id: "40", name: "귀찮은", category: "negative", emoji: "🛋️" },
  { id: "41", name: "기쁜", category: "positive", emoji: "😄" },
  { id: "42", name: "흥분된/황홀한", category: "positive", emoji: "🤩" },
  { id: "43", name: "안정된", category: "calm", emoji: "⚓" },
  { id: "44", name: "자신감있는", category: "positive", emoji: "💪" },
  { id: "45", name: "활기있는", category: "positive", emoji: "⚡" },
  { id: "46", name: "생기가도는", category: "positive", emoji: "🌱" },
  { id: "47", name: "편한/가벼운", category: "calm", emoji: "🎈" },
  { id: "48", name: "안심되는", category: "calm", emoji: "😌" },
  { id: "49", name: "명확해진", category: "calm", emoji: "💡" },
  { id: "50", name: "가슴뭉클한", category: "positive", emoji: "💖" },
  { id: "51", name: "우울한", category: "negative", emoji: "☁️" },
  { id: "52", name: "속상한", category: "negative", emoji: "😿" },
  { id: "53", name: "겁나는", category: "negative", emoji: "😨" },
  { id: "54", name: "미운", category: "negative", emoji: "😠" },
  { id: "55", name: "피곤한", category: "negative", emoji: "💤" },
  { id: "56", name: "억울한", category: "negative", emoji: "🥺" },
  { id: "57", name: "불편한", category: "negative", emoji: "😣" },
  { id: "58", name: "놀란", category: "negative", emoji: "😲" },
  { id: "59", name: "심란한", category: "negative", emoji: "🌀" },
  { id: "60", name: "무관심한", category: "calm", emoji: "😶" }
];

// 추가 감정 데이터 (61~70)
const extraEmotions = [
  { id: "61", name: "설레는", category: "positive", emoji: "💓", isExtra: true },
  { id: "62", name: "아련한", category: "calm", emoji: "🌌", isExtra: true },
  { id: "63", name: "씁쓸한", category: "negative", emoji: "☕", isExtra: true },
  { id: "64", name: "홀가분한", category: "calm", emoji: "🕊️", isExtra: true },
  { id: "65", name: "벅차오르는", category: "positive", emoji: "🎆", isExtra: true },
  { id: "66", name: "허전한", category: "negative", emoji: "🍂", isExtra: true },
  { id: "67", name: "벅찬", category: "positive", emoji: "🌈", isExtra: true },
  { id: "68", name: "멍한", category: "calm", emoji: "😶‍🌫️", isExtra: true },
  { id: "69", name: "평화로운", category: "calm", emoji: "🏡", isExtra: true },
  { id: "70", name: "울컥하는", category: "negative", emoji: "💧", isExtra: true }
];

// 통합 감정 데이터
const emotionsData = [...baseEmotions, ...extraEmotions];