// 기본 감정 데이터 (1~60)
const baseEmotions = [
  { id: "01", emoji: "🌿", name: "편안한", category: "calm", },
  { id: "02", emoji: "☀️", name: "따뜻한", category: "calm", },
  { id: "03", emoji: "👋", name: "반가운", category: "positive", },
  { id: "04", emoji: "🔍", name: "흥미로운", category: "positive", },
  { id: "05", emoji: "🧐", name: "궁금한", category: "positive", },
  { id: "06", emoji: "👑", name: "자랑스러운", category: "positive", },
  { id: "07", emoji: "☕", name: "느긋한", category: "calm", },
  { id: "08", emoji: "🥰", name: "행복한", category: "positive", },
  { id: "09", emoji: "🎉", name: "신나는", category: "positive", },
  { id: "10", emoji: "✨", name: "기대되는", category: "positive", },
  { id: "11", emoji: "🙏", name: "감사한", category: "positive", },
  { id: "12", emoji: "💥", name: "통쾌한", category: "positive", },
  { id: "13", emoji: "🌸", name: "다정한", category: "positive", },
  { id: "14", emoji: "😆", name: "재미있는", category: "positive", },
  { id: "15", emoji: "🥺", name: "감동한", category: "positive", },
  { id: "16", emoji: "❤️", name: "사랑스러운", category: "positive", },
  { id: "17", emoji: "🌟", name: "뿌듯한", category: "positive", },
  { id: "18", emoji: "😊", name: "만족스러운", category: "calm", },
  { id: "19", emoji: "🛡️", name: "든든한", category: "calm", },
  { id: "20", emoji: "🔥", name: "열중한", category: "positive", },
  { id: "21", emoji: "😳", name: "창피한/수줍은", category: "negative", },
  { id: "22", emoji: "💧", name: "슬픈", category: "negative", },
  { id: "23", emoji: "🥱", name: "지루한", category: "negative", },
  { id: "24", emoji: "😤", name: "답답한", category: "negative", },
  { id: "25", emoji: "💢", name: "짜증나는", category: "negative", },
  { id: "26", emoji: "🌧️", name: "서운한", category: "negative", },
  { id: "27", emoji: "💔", name: "마음이아픈", category: "negative", },
  { id: "28", emoji: "😟", name: "걱정스러운", category: "negative", },
  { id: "29", emoji: "🔋", name: "지친", category: "negative", },
  { id: "30", emoji: "😱", name: "무서운", category: "negative", },
  { id: "31", emoji: "😬", name: "긴장된", category: "negative", },
  { id: "32", emoji: "😰", name: "불안한", category: "negative", },
  { id: "33", emoji: "🎈", name: "외로운", category: "negative", },
  { id: "34", emoji: "😞", name: "실망스러운", category: "negative", },
  { id: "35", emoji: "😡", name: "화가난", category: "negative", },
  { id: "36", emoji: "🌧️", name: "후회스러운", category: "negative", },
  { id: "37", emoji: "😖", name: "불쾌한", category: "negative", },
  { id: "38", emoji: "🩹", name: "괴로운/고통스러운", category: "negative", },
  { id: "39", emoji: "🙇", name: "미안한", category: "negative", },
  { id: "40", emoji: "🛋️", name: "귀찮은", category: "negative", },
  { id: "41", emoji: "😄", name: "기쁜", category: "positive", },
  { id: "42", emoji: "🤩", name: "흥분된/황홀한", category: "positive", },
  { id: "43", emoji: "⚓", name: "안정된", category: "calm", },
  { id: "44", emoji: "💪", name: "자신감있는", category: "positive", },
  { id: "45", emoji: "⚡", name: "활기있는", category: "positive", },
  { id: "46", emoji: "🌱", name: "생기가도는", category: "positive", },
  { id: "47", emoji: "🎈", name: "편한/가벼운", category: "calm", },
  { id: "48", emoji: "😌", name: "안심되는", category: "calm", },
  { id: "49", emoji: "💡", name: "명확해진", category: "calm", },
  { id: "50", emoji: "💖", name: "가슴뭉클한", category: "positive", },
  { id: "51", emoji: "☁️", name: "우울한", category: "negative", },
  { id: "52", emoji: "😿", name: "속상한", category: "negative", },
  { id: "53", emoji: "😨", name: "겁나는", category: "negative", },
  { id: "54", emoji: "😠", name: "미운", category: "negative", },
  { id: "55", emoji: "💤", name: "피곤한", category: "negative", },
  { id: "56", emoji: "🥺", name: "억울한", category: "negative", },
  { id: "57", emoji: "😣", name: "불편한", category: "negative", },
  { id: "58", emoji: "😲", name: "놀란", category: "negative", },
  { id: "59", emoji: "🌀", name: "심란한", category: "negative", },
  { id: "60", emoji: "😶", name: "무관심한", category: "calm", }
];

// 추가 감정 데이터 (61~70)
const extraEmotions = [
  { id: "61", emoji: "💓", name: "설레는", category: "positive",  isExtra: true },
  { id: "62", emoji: "🌌", name: "아련한", category: "calm",  isExtra: true },
  { id: "63", emoji: "☕", name: "씁쓸한", category: "negative",  isExtra: true },
  { id: "64", emoji: "🕊️", name: "홀가분한", category: "calm",  isExtra: true },
  { id: "65", emoji: "🎆", name: "벅차오르는", category: "positive",  isExtra: true },
  { id: "66", emoji: "🍂", name: "허전한", category: "negative",  isExtra: true },
  { id: "67", emoji: "🌈", name: "벅찬", category: "positive",  isExtra: true },
  { id: "68", emoji: "😶‍🌫️", name: "멍한", category: "calm",  isExtra: true },
  { id: "69", emoji: "🏡", name: "평화로운", category: "calm",  isExtra: true },
  { id: "70", emoji: "💧", name: "울컥하는", category: "negative",  isExtra: true }
];

// 통합 감정 데이터
const emotionsData = [...baseEmotions, ...extraEmotions];